import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

export function getPackageVersion(): string {
  const currentDir = dirname(fileURLToPath(import.meta.url));
  const packagePath = join(currentDir, "..", "..", "package.json");
  const pkg = JSON.parse(readFileSync(packagePath, "utf8")) as { version: string };
  return pkg.version;
}

export function getHelpText(): string {
  return [
    "benjamin-docs",
    "",
    "Persistent project memory for AI coding agents.",
    "",
    "Turns your repo into living project knowledge that agents read, follow, and update while they work.",
    "",
    "Start a new session with pointers to context: purpose, progress, decisions, conventions, risks, next actions, and handoff notes.",
    "",
    "Main commands:",
    "  benjamin-docs init    Set up repo-local project memory.",
    "  benjamin-docs ready   Run deterministic project-memory readiness checks.",
    "  benjamin-docs export  Create guided handoff and summary exports.",
    "  benjamin-docs upgrade Refresh Benjamin-owned files after a CLI update.",
    "  benjamin-docs help    Show this guide.",
    "",
    "If you are starting from a chat, ask your agent:",
    "  Use the benjamin-docs skill to create a project from this chat.",
    "",
    "If you are inside a project, run:",
    "  benjamin-docs init",
    "",
    "In an app or codebase, init auto-detects codebase memory, installs agent guidance, and offers agent session hooks.",
    "",
    "To supply a compact pointer/context packet at session start in Claude Code, Codex, and Cursor:",
    "  benjamin-docs hooks install",
    "",
    "To give MCP-capable agents native memory tools (search, read, validated writes):",
    "  benjamin-docs mcp install",
    "",
    "To see which docs fell behind the code they describe:",
    "  benjamin-docs drift",
    "",
    "After docs are captured, refresh derived views and check readiness:",
    "  benjamin-docs views",
    "  benjamin-docs ready",
    "",
    "To create a local feature, app, or handoff export:",
    "  benjamin-docs export",
    "",
    "Then ask your agent:",
    "  Read the Benjamin Docs project memory, capture the current baseline, and keep it updated as you work.",
    "",
    "For Claude.ai or Claude Desktop skill upload:",
    "  benjamin-docs package-skill",
    "",
    "For every command, run the interactive drawer:",
    "  benjamin-docs commands",
  ].join("\n");
}

export function getIntroductionText(): string {
  return [
    "benjamin-docs gives AI coding agents persistent project memory.",
    "",
    "It turns your repo into living project knowledge that agents read, follow, and update while they work.",
    "",
    "Start a new coding session and the agent can read:",
    "- what the project is",
    "- where work stopped",
    "- decisions",
    "- open questions",
    "- conventions and risks",
    "- code maps and handoff notes",
    "- what to do next",
    "",
    "Markdown is the storage format. Continuity is the product.",
    "",
    "No cloud. No dashboard. No transcript dump.",
    "",
    "Install or refresh the bundled agent skill:",
    "  benjamin-docs install-skill",
    "",
    "Inside a project, run:",
    "  benjamin-docs init",
    "",
    "In an app or codebase, init auto-detects codebase memory, installs agent guidance, and offers agent session hooks.",
    "",
    "With hooks installed, session-start supplies a compact pointer/context packet to Claude Code, Codex, and Cursor.",
    "Agents maintain project memory during normal work, and benjamin-docs drift reports watched docs behind committed code.",
    "",
    "After useful docs exist, generate Memory Views:",
    "  benjamin-docs views",
    "",
    "Then run the deterministic readiness dimensions:",
    "  benjamin-docs ready",
    "",
    "From any chat, ask your agent:",
    "  Use the benjamin-docs skill to create a project from this chat.",
    "",
    "The agent should ask before writing files and suggest:",
    "  ~/Documents/Benjamin Docs/<Project Name>",
    "",
    "For the exact chat-to-project prompt, run:",
    "  benjamin-docs chat-project",
    "",
    "Main commands:",
    "  benjamin-docs init",
    "  benjamin-docs ready",
    "  benjamin-docs export",
    "  benjamin-docs help",
    "",
    "Useful project-memory refresh flow:",
    "  benjamin-docs init",
    "  benjamin-docs views",
    "  benjamin-docs ready",
    "",
    "For the full interactive command drawer, run:",
    "  benjamin-docs commands",
    "",
    "Then ask your agent:",
    "  Read the Benjamin Docs project memory, capture the current baseline, and keep it updated as you work.",
  ].join("\n");
}

export function getInitHelpText(): string {
  return [
    "benjamin-docs init",
    "",
    "Set up local project memory.",
    "",
    "For most people:",
    "  benjamin-docs init",
    "",
    "What it does:",
    "- In an interactive terminal, asks what you are setting up.",
    "- In an obvious codebase, defaults to codebase memory and agent guidance.",
    "- Preserves existing docs and existing AGENTS.md content.",
    "",
    "Automation flags:",
    "  benjamin-docs init --mode planning",
    "  benjamin-docs init --mode codebase",
    "  benjamin-docs init --mode feature --feature <slug>",
    "  benjamin-docs init --agent-contract",
    "  benjamin-docs init --agent-contract --children",
    "  benjamin-docs init --no-agent-contract",
    "  benjamin-docs init --hooks",
    "  benjamin-docs init --no-hooks",
    "",
    "Tip: teach humans `benjamin-docs init`; use flags for scripts and agents.",
  ].join("\n");
}

export function getAnchorHelpText(): string {
  return [
    "benjamin-docs anchor",
    "",
    "Link stable names to important code files.",
    "",
    "Commands:",
    "  benjamin-docs anchor add <id> <file>",
    "  benjamin-docs anchor list",
    "",
    "Examples:",
    "  benjamin-docs anchor add homepage pages/index.js",
    "  benjamin-docs anchor list",
  ].join("\n");
}

export function getScopeHelpText(): string {
  return [
    "benjamin-docs scope",
    "",
    "Create focused docs for a feature, change, or plan.",
    "",
    "Commands:",
    "  benjamin-docs scope create feature <slug>",
    "  benjamin-docs scope status <id> <status>",
    "",
    "Statuses: draft, review, approved, stale, archived.",
    "Archived and stale scopes drop out of generated Memory Views.",
    "",
    "Examples:",
    "  benjamin-docs scope create feature checkout-redesign",
    "  benjamin-docs scope status checkout-redesign archived",
  ].join("\n");
}
